<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RickAndMorty.DB\RickAndMorty.DB.csproj" />
    <ProjectReference Include="..\RickAndMorty.DTO\RickAndMorty.DTO.csproj" />
  </ItemGroup>

</Project>
